### ISSUE TITLE
Compiling with morphir-elm  no unification rules to apply error

### ISSUE THREAD

**Issue by ingjavierbarrios** [finos/morphir-elm#349]
**Describe the bug**
When compiling using `morphir-elm` having the following error:
```javascript
Error: [
  [
    "errors_in_source_file",
    "Example",
    [
      {
        "errorMessage": "Type error in value 'f': Could not unify '{ list1 : Morphir.SDK:List:list ( var_0_1, Morphir.SDK:Basics:float ), list2 : Morphir.SDK:List:list ( var_0_2, Morphir.SDK:List:list ( var_0_1, Morphir.SDK:Basics:float ) ) } as Morphir.Reference.Model:Example:result var_0_1 var_0_2' with '{ list1 : Morphir.SDK:List:list var_5_1, list2 : Morphir.SDK:List:list var_6_1 }' because there are no unification rules to apply",
        "sourceLocations": []
      }
    ]
  ]
]
```
**To Reproduce**
Use the following example
```javascript

type alias Result a b =
    { list1: List (a, Float)
     ,list2: List (b, List (a, Float ))
    }

f: (a -> Float ) -> List a -> Result a b
f _ _ =
    { list1 =
        []
    , list2 =
        []
    }

```
**Version:** 
 - Version morphir-elm 2.16.3

**Comment by AttilaMihaly** [comment]
I was able to reproduce the issue and minimized the sample down to this:

```elm
type alias Result a = { foo : List a }


f : Result a
f =
    { foo = [] }
```

Which produces the following error:

>Type error in value 'f': Could not unify '{ foo : Morphir.SDK:List:list var_t_0_1 } as Morphir.Reference.Model:Issues.Issue349:result var_t_0_1' with '{ foo : Morphir.SDK:List:list var_t_2_1 }' because there are no unification rules to apply

Breaking it up to read better, these two cannot be unified:

- `{ foo : Morphir.SDK:List:list var_t_0_1 } as Morphir.Reference.Model:Issues.Issue349:result var_t_0_1`
- `{ foo : Morphir.SDK:List:list var_t_2_1 }`

While the two look similar and should certainly unify the unification is not that straightforward since one is a type application:

- `MetaApply (MetaAlias "result" (MetaRecord ...)) (MetaVar "t_0_1")`
- `MetaRecord ...`

Unfortunately this is not just a missing unification rule. It seems that in order to support type aliases with type arguments we need to change our approach which is currently simply keeping track of a list of aliases:

https://github.com/finos/morphir-elm/blob/81abc8ab6fa10f167eb4e40cdc262290963e77cf/src/Morphir/Type/Solve.elm#L189-L190

We need to change this to also keep track of type arguments so that in a situation like the above we can say `Result Int` is the same as `{ foo : Int }`.
